config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users, only: :show
  resources :listings, except: :index
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  validates :price, :location, :property_type, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :listings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @listings = Listing.all
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
  end

  def new
    @listing = Listing.new
  end

  def create
    @user = User.find(current_user.id)
    @listing = @user.listings.new(listing_params)
    if @listing.save
      flash[:success] = "Listing Successfully Added!"
      redirect_to root_path
    else
      flash[:danger] = "There was a problem creating your listing, please try again."
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      flash[:success] = "Listing Succesfully Updated"
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @listing = Listing.find(params[:id])
    @listing.destroy
    flash[:danger] = "Listing Successfully Deleted!"
    redirect_to user_path(@user)
  end

private
  def listing_params
    params.require(:listing).permit(:price, :location, :property_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= link_to "Add Listing", new_listing_path %>

<% if @listings.any? %>
  <h4>Here are some listings:</h4>
  <ul>
    <% @listings.each do |listing| %>
      <li>
        <hr>
        Price: $<%= listing.price %><br>
        Location: <%= listing.location %><br>
        Property Type: <%= listing.property_type %><br>
        <hr>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no listings yet!</p>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BearDnd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <ul class="main-nav list-unstyled">
          <li><%= link_to "Bear DnD", root_path, class: 'navbar-brand' %></li>
        </ul>
      </div>
      <ul class="nav navbar-nav navbar-left">
        <% if user_signed_in? %>
          <li>Logged in as: <strong><%= link_to current_user.email, user_path(current_user) %></strong></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render 'form' %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= render "layouts/errors", object: @listing %>

<%= form_for @listing do |f| %>
  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control', required: true, autofocus: true %>
  <%= f.label :price %>
  <%= f.number_field :price, class: 'form-control', required: true %>
  <%= f.label :property_type %>
  <%= f.text_field :property_type, size: "30x6", class: 'form-control', required: true %>
  <br>
  <%= f.submit class: 'btn btn-success', method: "post" %>
<% end %>

app/views/users/show.html.erb
<% if current_user.listings.any? %>
  <h4>Here are <%= current_user.email %>'s Listings:</h4>
  <ul>
    <% current_user.listings.each do |listing| %>
      <li>
        <hr>
        Price: $<%= listing.price %><br>
        Location: <%= listing.location %><br>
        Property Type: <%= listing.property_type %><br>
        <%= link_to "Edit", edit_listing_path(listing.id), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", listing_path(listing.id), class: "btn btn-xs btn-danger",
                                                data: {confirm: "You sure you want to delete",
                                                       method: "delete"} %>
        <hr>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no listings yet!</p>
<% end %>